### ISSUE TITLE
复现问题

### ISSUE THREAD

**Issue by Dx3281101** [wengwenchao123/PM-DMNet#1]
您好，
![image](https://github.com/user-attachments/assets/b272c0f8-0b07-4ed8-b140-aaaebbfe1e90)
当我尝试复现时，会出现下面的错误，能请教一下如何解决吗

**Comment by wengwenchao123** [comment]
这是命令行命令输错后容易出来的情况，你命令行的代码有吗，这个大概率是数据集的那个没输对

**Comment by wengwenchao123** [comment]
我在readme里面增加了一个命令行的具体案例，你可以用那个跑跑看

**Comment by wengwenchao123** [comment]
之前在type那边可能没写好例子，可能存在误导，现在改过来了

**Comment by wengwenchao123** [comment]
如果解决了麻烦说一声，有问题的话也说一下，我再找一下原因

**Comment by Dx3281101** [comment]
谢谢您的回复，已经解决问题了

**Comment by wengwenchao123** [comment]
好的，不客气
