### ISSUE TITLE
可视化

### ISSUE THREAD

**Issue by Dx3281101** [wengwenchao123/PM-DMNet#2]
![image](https://github.com/user-attachments/assets/9282992e-161c-4369-a4b9-f65dd5aa64fd)
您好，请教一个问题，我想知道如何才能直观地看到真实值和预测结果（针对某个节点）？非常感谢

**Comment by wengwenchao123** [comment]
额，你是想问这个图是怎么画出来的吗

**Comment by wengwenchao123** [comment]
如果是想问这个真实值和预测值该怎么画出来的话，我们test的时候，我们是按照顺序进行预测的，没有打乱顺序，所以我们可以将真实值和预测值的结果保存下来，然后找到对应节点进行画图

**Comment by Dx3281101** [comment]
非常感谢您的回复，我想看代码层面如何实现的。如果方便可以发到邮箱723445197@qq.com,感谢！

**Comment by Dx3281101** [comment]
> 如果是想问这个真实值和预测值该怎么画出来的话，我们test的时候，我们是按照顺序进行预测的，没有打乱顺序，所以我们可以将真实值和预测值的结果保存下来，然后找到对应节点进行画图

![image](https://github.com/user-attachments/assets/7c79ad1a-98dc-4c54-830b-2b3e291d3126)
![image](https://github.com/user-attachments/assets/aab0415a-bdd2-466e-99b2-1d7a5ba6fa08)

非常感谢您的解答，已经将真实值和预测值的结果保存下来，如果要画出下面的图，我该如何选择时间步骤呢？

**Comment by wengwenchao123** [comment]
> > 如果是想问这个真实值和预测值该怎么画出来的话，我们test的时候，我们是按照顺序进行预测的，没有打乱顺序，所以我们可以将真实值和预测值的结果保存下来，然后找到对应节点进行画图
> 
> ![image](https://private-user-images.githubusercontent.com/104825467/384655675-7c79ad1a-98dc-4c54-830b-2b3e291d3126.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMDkzODEsIm5iZiI6MTczMTIwOTA4MSwicGF0aCI6Ii8xMDQ4MjU0NjcvMzg0NjU1Njc1LTdjNzlhZDFhLTk4ZGMtNGM1NC04MzBiLTJiM2UyOTFkMzEyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwMzI0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjU0N2ZkZGI0MWJmNmZiNDRiNTZmNTMwMjQzNWZhYjRkNTRmYWUyODk5Yjc2YmQwN2M4M2ZiZDBmYjk1NDBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rjbVD2hUFpvwLSl9obJA5x4OaL3s6or3isfgL1zDsn4) ![image](https://private-user-images.githubusercontent.com/104825467/384655707-aab0415a-bdd2-466e-99b2-1d7a5ba6fa08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMDkzODEsIm5iZiI6MTczMTIwOTA4MSwicGF0aCI6Ii8xMDQ4MjU0NjcvMzg0NjU1NzA3LWFhYjA0MTVhLWJkZDItNDY2ZS05OWIyLTFkN2E1YmE2ZmEwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwMzI0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNWVlYmU1YjU0ZTNjOTkzOWVhZjVhN2I0OWIxYTMxZDk2NjAxNDExYzBjM2YxMWNlY2I2YTk2N2YxNzQ3MTI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.biB65tnxDMOSTQkoddLj0eWhYOo5Ghu6wxHWvqcDbu0)
> 
> 非常感谢您的解答，已经将真实值和预测值的结果保存下来，如果要画出下面的图，我该如何选择时间步骤呢？

你好，我把代码发到你邮箱里去了，有两个，一个是画多变量数据集的图的，一个实话真实值和预测值的图的，你看看有没有收到
另外这个图不是我的，但是这个图在python里没法画的，我认识的一个大佬画过这种图，他跟我说是中间那个小图p上去的

**Comment by Dx3281101** [comment]
代码已经收到，非常感谢您的帮助和解答！
